== Start Multiple Containers with Docker Compose

=== Install Docker Compose
Follow the instruction in https://docs.docker.com/compose/install/.

=== Build or Pull Docker Image

==== Build
If you build centos-ssh image, follow [https://github.com/kinogmt/docker-containers/blob/master/centos-ssh/readme.adoc[this] instruction.

==== Pull
Pull Docker image from public repository and tag it with shorter name like this:

--------------------------------
% docker pull quay.io/cloudian/centos-ssh
% docker tag quay.io/cloudian/centos-ssh centos-ssh
--------------------------------

=== docker-compose.yml

Following example of docker-compose.yml is for service named "centos"
using image named "centos-ssh" which is built or pulled above.

--------------------------
centos:
  image: centos-ssh
  hostname: c0
  mem_limit: 4000000000
  privileged: true
--------------------------

See https://docs.docker.com/compose/compose-file/ for detail
of compose file syntax.


=== Start Containers

Starting multiple containers using docker-compose *scale* command.
For example, following command will start 3 containers for

----------------------------------------------------------
% docker-compose scale centos=3
----------------------------------------------------------


=== Setup IP Addresses
==== Get IP Addresses
Get IP Addresses of containers using https://github.com/kinogmt/docker-containers/blob/master/centos-ssh/hosts.sh[hosts.sh].

----------------
% ./hosts.sh 3
172.17.0.3 c1.localdomain c1
172.17.0.4 c2.localdomain c2
172.17.0.4 c3.localdomain c3
% ./hosts.sh 3 > ./hosts
----------------


==== Add IP Addresses to /etc/hosts of Docker Host
Edit /etc/hosts of Docker Host to include the IP addresses of containers.

==== Add IP Addresses to /etc/hosts of Docker Containers
Add IP addresses of containers to /etc/hosts of each container
using following commands, for example.

--------------------------------
% cat ./hosts|ssh root@c1 "cat >> /etc/hosts"
% cat ./hosts|ssh root@c2 "cat >> /etc/hosts"
% cat ./hosts|ssh root@c3 "cat >> /etc/hosts"
--------------------------------

==== Fix "hostname" of Containers

--------------------------------
% ssh c1 hostname c1
% ssh c2 hostname c2
% ssh c3 hostname c3
--------------------------------
