== Start Multiple Containers with Docker Compose
This is an example to start some Docker containers with SSH access
as the basis for multi-node cluster deployment.

=== Install Docker

Read link:install.adoc[this document]
for installation of Docker.

=== create a network for containers

-----------------------------------
% docker network create w_net1
-----------------------------------

=== docker-compose.yml

Following example of docker-compose.yml is for service named "centos"
using Docker image quay.io/cloudian/centos-ssh.

[NOTE]
Password of root on quay.io/cloudian/centos-ssh is "password".

--------------------------
version: "2"
services:
  centos:
    image: quay.io/cloudian/centos-ssh:jdk8
    hostname: cld0  
    privileged: true
    dns:
      - 127.0.0.1
      - 8.8.8.8
    dns_search:
      - localdomain
    networks:
      - net1
networks:
  net1:
--------------------------

See https://docs.docker.com/compose/compose-file/ for detail
of compose file syntax.


=== Start Containers

Starting multiple containers using docker-compose *scale* command.
For example, following command will start 1 container first
and scale it up to 3 containers of *centos*
service defined in the docker-compose.yml above.

----------------------------------------------------------
% docker-compose -p=w scale centos=1
% docker-compose -p=w scale centos=3
----------------------------------------------------------


=== Get IP Addresses
Get IP Addresses of containers using link:hosts.sh[hosts.sh].

----------------
% ./hosts.sh
172.17.0.2 cld1.localdomain cld1
172.17.0.3 cld2.localdomain cld2
172.17.0.4 cld3.localdomain cld3
% ./hosts.sh > ./hosts
----------------


