== Start Multiple Containers with Docker Compose

=== Install Docker Compose
Follow the instruction in https://docs.docker.com/compose/install/.

=== Pull Docker Image
Pull Docker image from repository and tag it with shorter name like this:

--------------------------------
% docker pull quay.io/cloudian/centos-ssh:6.7
% docker tag quay.io/cloudian/centos-ssh:6.7 centos-ssh:6.7
--------------------------------

=== docker-compose.yml

--------------------------
centos:
  image: centos-ssh:6.7
  hostname: c0
  mem_limit: 4000000000
  privileged: true
--------------------------


=== Start Master Container

Starting master container which includes port mapping.

Run following command in the directory with docker-compose.yml file.

It will start the master container
which includes port mapping for 80 and 8443.

----------------------------------------------------------
% docker-compose -p m run -d -p 8443:8443 -p 80:80 centos
----------------------------------------------------------

=== Start Worker Containers

Starting 3 worker containers.

----------------------------------------------------------
% docker-compose scale centos=3
----------------------------------------------------------


=== Setup IP Addresses
==== Get IP Addresses
Get IP Addresses of containers using https://github.com/kinogmt/docker-containers/blob/master/centos-ssh/hosts.sh[hosts.sh].

----------------
% ./hosts.sh
usage: ./hosts.sh <number-of-containers>
% ./hosts.sh 4 > ./hosts
% cat ./hosts
172.17.0.2 c0.localdomain c0
172.17.0.3 c1.localdomain c1
172.17.0.4 c2.localdomain c2
172.17.0.5 c3.localdomain c3
----------------

[NOTE]
Argument of the test.sh is the number of containers started,
including both master and workers. "c0" is for the master and
"c1", "c2", ... are for the workers.

==== Add IP Addresses to /etc/hosts of Docker Host
Edit /etc/hosts of Docker Host to include the IP addresses of containers.

==== Add IP Addresses to /etc/hosts of Docker Containers
Add IP addresses of containers to /etc/hosts of each container
using following commands, for example.

--------------------------------
% cat ./hosts|ssh root@c0 "cat >> /etc/hosts"
% cat ./hosts|ssh root@c1 "cat >> /etc/hosts"
% cat ./hosts|ssh root@c2 "cat >> /etc/hosts"
% cat ./hosts|ssh root@c3 "cat >> /etc/hosts"
--------------------------------

