== Start Multiple Containers with Docker Compose
This is an example to start some Docker containers with SSH access
as the basis for multi-node cluster deployment.

Instructions below are assuming basic idea about Docker and
"Docker Engine" and "Docker Compose" are already installed.
If not, please read https://docs.docker.com/ first.


=== Build or Pull Docker Image
Prepare Docker image for CentOS with SSH access.
There are two ways - build yourself or pull it from public repository.

==== Build
If you build centos-ssh image, follow https://github.com/kinogmt/docker-containers/blob/master/centos-ssh/readme.adoc[this] instruction.

==== Pull
Pull Docker image from public repository and tag it with shorter name like this:

--------------------------------
% docker pull quay.io/cloudian/centos-ssh:6.7
% docker tag quay.io/cloudian/centos-ssh:6.7 centos-ssh:6.7
--------------------------------

=== docker-compose.yml

Following example of docker-compose.yml is for service named "centos"
using image named "centos-ssh" which is built or pulled above.

--------------------------
centos:
  image: centos-ssh:6.7
  hostname: c000
  mem_limit: 4000000000
  privileged: true
--------------------------

See https://docs.docker.com/compose/compose-file/ for detail
of compose file syntax.


=== Start Containers

Starting multiple containers using docker-compose *scale* command.
For example, following command will start 3 containers for *centos*
service defined in the docker-compose.yml above.

----------------------------------------------------------
% docker-compose -p=w scale centos=3
----------------------------------------------------------


=== Setup IP Addresses
==== Get IP Addresses
Get IP Addresses of containers using https://github.com/kinogmt/docker-containers/blob/master/centos-ssh/hosts.sh[hosts.sh].

----------------
% ./hosts.sh
172.17.0.2 c1.localdomain c1
172.17.0.3 c2.localdomain c2
172.17.0.4 c3.localdomain c3
% ./hosts.sh > ./hosts
----------------


==== Add IP Addresses to /etc/hosts of Docker Host
Edit /etc/hosts of Docker Host to include the IP addresses of containers.

==== SSH authorized_keys
Optionally you can put your ssh authorized_keys to containers
like following example.

----------------------------------------------
% for i in 1 2 3;do scp ~/.ssh/authorized_keys root@c$i:.ssh/; done
----------------------------------------------

Default root password is set as "password" in centos-ssh image.
You can disables this password for root after successfully putting
your public key to containers.


==== Add IP Addresses to /etc/hosts of Docker Containers
Add IP addresses of containers to /etc/hosts of each container
using following commands, for example.

--------------------------------
% cat ./hosts|ssh root@c1 "cat >> /etc/hosts"
% cat ./hosts|ssh root@c2 "cat >> /etc/hosts"
% cat ./hosts|ssh root@c3 "cat >> /etc/hosts"
--------------------------------

Or this:
--------------------------------
% for i in 1 2 3;do cat ./hosts|ssh root@c$i "cat >> /etc/hosts"; done
--------------------------------


==== Fix "hostname" of Containers

--------------------------------
% ssh root@c1 hostname c1
% ssh root@c2 hostname c2
% ssh root@c3 hostname c3
--------------------------------

Or this:
--------------------------------
% for i in 1 2 3; do ssh root@c$i hostname c$i; done
--------------------------------
