== Start Multiple Containers with Docker Compose
This is an example to start some Docker containers with SSH access
as the basis for multi-node cluster deployment.

=== Install Docker

Read link:install.adoc[this document]
for installation of Docker.


=== docker-compose.yml

Following example of docker-compose.yml is for service named "centos"
using image named "centos-ssh" which is built or pulled above.

--------------------------
centos:
  image: quay.io/cloudian/centos-ssh
  hostname: c000
  mem_limit: 8000000000
  privileged: true
  dns:
    - 127.0.0.1
    - 8.8.8.8
  dns_search:
    - localdomain
--------------------------

See https://docs.docker.com/compose/compose-file/ for detail
of compose file syntax.


=== Start Containers

Starting multiple containers using docker-compose *scale* command.
For example, following command will start 1 container first
and scale it up to 3 containers of *centos*
service defined in the docker-compose.yml above.

----------------------------------------------------------
% docker-compose -p=w scale centos=1
% docker-compose -p=w scale centos=3
----------------------------------------------------------


=== Setup IP Addresses
==== Get IP Addresses
Get IP Addresses of containers using https://github.com/kinogmt/docker-containers/blob/master/centos-ssh/hosts.sh[hosts.sh].

----------------
% ./hosts.sh
172.17.0.2 cld1.localdomain cld1
172.17.0.3 cld2.localdomain cld2
172.17.0.4 cld3.localdomain cld3
% ./hosts.sh > ./hosts
----------------


==== Add IP Addresses to /etc/hosts of Docker Host
Edit /etc/hosts of Docker Host to include the IP addresses of containers.

==== SSH authorized_keys
Optionally you can put your ssh authorized_keys to containers
like following example.

----------------------------------------------
% for i in 1 2 3;do scp ~/.ssh/authorized_keys root@cld$i:.ssh/; done
----------------------------------------------

Default root password is set as "password" in centos-ssh image.
You can disables this password for root after successfully putting
your public key to containers.


==== Add IP Addresses to /etc/hosts of Docker Containers
Add IP addresses of containers to /etc/hosts of each container
using following commands, for example.

--------------------------------
% cat ./hosts|ssh root@cld1 "cat >> /etc/hosts"
% cat ./hosts|ssh root@cld2 "cat >> /etc/hosts"
% cat ./hosts|ssh root@cld3 "cat >> /etc/hosts"
--------------------------------

Or this:
--------------------------------
% for i in 1 2 3;do cat ./hosts|ssh root@cld$i "cat >> /etc/hosts"; done
--------------------------------


==== Fix "hostname" of Containers

--------------------------------
% ssh root@cld1 hostname cld1
% ssh root@cld2 hostname cld2
% ssh root@cld3 hostname cld3
--------------------------------

Or this:
--------------------------------
% for i in 1 2 3; do ssh root@cld$i hostname cld$i; done
--------------------------------
