#!/bin/sh
if [ $# -ne 3 ];
then
    echo "usage: $0 <package-file> <license-file> <survey-file>"
        exit 1
        fi


PKG=$1
LIC=$2
SURV=$3
INST=./install.sh

scp $PKG $LIC $SUR $INST root@c1:/root/

ssh -A root@c1 /root/install.sh
